// <auto-generated />
using EntrainementDS.Models.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntrainementDS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251010142005_MigrationDb")]
    partial class MigrationDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntrainementDS.Models.EntityFramework.Commande", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("COM_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCommande"));

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("UTI_ID");

                    b.Property<int>("Montant")
                        .HasColumnType("integer")
                        .HasColumnName("COM_MONTANT");

                    b.Property<string>("NomArticle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("COM_NOMARTICLE");

                    b.HasKey("IdCommande")
                        .HasName("PK_COM");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("T_E_COMMANDE_COM", "public");
                });

            modelBuilder.Entity("EntrainementDS.Models.EntityFramework.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UTI_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UTI_CODEPOSTAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UTI_NOM");

                    b.Property<int>("NumeroRue")
                        .HasColumnType("integer")
                        .HasColumnName("UTI_NUMERORUE");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UTI_PRENOM");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("UTI_RUE");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UTI_VILLE");

                    b.HasKey("IdUtilisateur")
                        .HasName("PK_UTI");

                    b.ToTable("T_E_UTILISATEUR_UTI", "public");
                });

            modelBuilder.Entity("EntrainementDS.Models.EntityFramework.Commande", b =>
                {
                    b.HasOne("EntrainementDS.Models.EntityFramework.Utilisateur", "Utilisateur")
                        .WithMany("Commandes")
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK_COM_UTI");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("EntrainementDS.Models.EntityFramework.Utilisateur", b =>
                {
                    b.Navigation("Commandes");
                });
#pragma warning restore 612, 618
        }
    }
}
